# Form implementation generated from reading ui file 'ventana_agregar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(780, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setStyleSheet("QFrame{\n"
"    background-color: #0068BC;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font: 20pt \"Swis721 BlkCn BT\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background-color:#5DADE2; \n"
"    \n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_regresar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_regresar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../models/regresar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setIconSize(QtCore.QSize(40, 40))
        self.btn_regresar.setObjectName("btn_regresar")
        self.horizontalLayout.addWidget(self.btn_regresar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(parent=self.frame_superior)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(139, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../models/minimizar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_minimizar.setIcon(icon1)
        self.btn_minimizar.setIconSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_achicar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_achicar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../models/hacerchico.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_achicar.setIcon(icon2)
        self.btn_achicar.setIconSize(QtCore.QSize(40, 40))
        self.btn_achicar.setObjectName("btn_achicar")
        self.horizontalLayout.addWidget(self.btn_achicar)
        self.btn_agrandar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_agrandar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../models/hacergrande.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_agrandar.setIcon(icon3)
        self.btn_agrandar.setIconSize(QtCore.QSize(40, 40))
        self.btn_agrandar.setObjectName("btn_agrandar")
        self.horizontalLayout.addWidget(self.btn_agrandar)
        self.btn_cerrar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_cerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../models/cerrar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cerrar.setIcon(icon4)
        self.btn_cerrar.setIconSize(QtCore.QSize(40, 40))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_cuerpo = QtWidgets.QFrame(parent=self.frame)
        self.frame_cuerpo.setStyleSheet("background-color: #99D8DD")
        self.frame_cuerpo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cuerpo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cuerpo.setObjectName("frame_cuerpo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_cuerpo)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_labels = QtWidgets.QFrame(parent=self.frame_cuerpo)
        self.frame_labels.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_labels.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font: 20pt \"Swis721 BlkCn BT\";\n"
"    text-align: right;\n"
"}")
        self.frame_labels.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_labels.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_labels.setObjectName("frame_labels")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_labels)
        self.verticalLayout_3.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_labels)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_labels)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_labels)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_labels)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_labels)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        spacerItem9 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_labels)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.horizontalLayout_2.addWidget(self.frame_labels)
        self.frame_llenado = QtWidgets.QFrame(parent=self.frame_cuerpo)
        self.frame_llenado.setStyleSheet("QFrame{\n"
"    background-color: #C0E4E5\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(232, 232, 232);\n"
"    border-radius: 10px;\n"
"    height: 30px;\n"
"    font: 20pt \"Swis721 BlkCn BT\";\n"
"    \n"
"}")
        self.frame_llenado.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_llenado.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_llenado.setObjectName("frame_llenado")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_llenado)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_4.addItem(spacerItem11)
        self.LnEdit_id = QtWidgets.QLineEdit(parent=self.frame_llenado)
        self.LnEdit_id.setObjectName("LnEdit_id")
        self.verticalLayout_4.addWidget(self.LnEdit_id)
        spacerItem12 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.LnEdit_producto = QtWidgets.QLineEdit(parent=self.frame_llenado)
        self.LnEdit_producto.setObjectName("LnEdit_producto")
        self.verticalLayout_4.addWidget(self.LnEdit_producto)
        spacerItem13 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.LnEdit_descripcion = QtWidgets.QLineEdit(parent=self.frame_llenado)
        self.LnEdit_descripcion.setObjectName("LnEdit_descripcion")
        self.verticalLayout_4.addWidget(self.LnEdit_descripcion)
        spacerItem14 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.LnEdit_categoria = QtWidgets.QLineEdit(parent=self.frame_llenado)
        self.LnEdit_categoria.setObjectName("LnEdit_categoria")
        self.verticalLayout_4.addWidget(self.LnEdit_categoria)
        spacerItem15 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem15)
        self.LnEdit_stockactual = QtWidgets.QLineEdit(parent=self.frame_llenado)
        self.LnEdit_stockactual.setObjectName("LnEdit_stockactual")
        self.verticalLayout_4.addWidget(self.LnEdit_stockactual)
        spacerItem16 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.LnEdit_stockminimo = QtWidgets.QLineEdit(parent=self.frame_llenado)
        self.LnEdit_stockminimo.setObjectName("LnEdit_stockminimo")
        self.verticalLayout_4.addWidget(self.LnEdit_stockminimo)
        spacerItem17 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_4.addItem(spacerItem17)
        self.btn_agregar = QtWidgets.QPushButton(parent=self.frame_llenado)
        self.btn_agregar.setStyleSheet("QPushButton{\n"
"    background-color: #0068BC;       \n"
"    color: #FFFFFF;                    /* Texto blanco */\n"
"    border: none;                    /* Sin borde de línea */\n"
"    border-radius: 12px;             /* Bordes redondeados */\n"
"    padding: 10px 20px;              /* Relleno interno */\n"
"    font: bold 12pt \"Arial\"; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5DADE2;       /* Color cuando el mouse pasa encima */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../models/agregar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_agregar.setIcon(icon5)
        self.btn_agregar.setIconSize(QtCore.QSize(30, 30))
        self.btn_agregar.setObjectName("btn_agregar")
        self.verticalLayout_4.addWidget(self.btn_agregar)
        self.horizontalLayout_2.addWidget(self.frame_llenado)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.addWidget(self.frame_cuerpo)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Ventana Agregar producto"))
        self.label_2.setText(_translate("Form", "ID del nuevo producto"))
        self.label_3.setText(_translate("Form", "Nombre del nuevo producto"))
        self.label_4.setText(_translate("Form", "Descripcion del producto"))
        self.label_5.setText(_translate("Form", "Categoria del producto"))
        self.label_6.setText(_translate("Form", "Stock actual"))
        self.label_7.setText(_translate("Form", "Stock minimo"))
        self.LnEdit_id.setPlaceholderText(_translate("Form", "ID..."))
        self.LnEdit_producto.setPlaceholderText(_translate("Form", "Nombre..."))
        self.LnEdit_descripcion.setPlaceholderText(_translate("Form", "Descripcion..."))
        self.LnEdit_categoria.setPlaceholderText(_translate("Form", "Categoria..."))
        self.LnEdit_stockactual.setPlaceholderText(_translate("Form", "Stock (positivo)..."))
        self.LnEdit_stockminimo.setPlaceholderText(_translate("Form", "Stock (minimo)..."))
        self.btn_agregar.setText(_translate("Form", "Agregar"))
