# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 591)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color:#ffffff;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_barra = QtWidgets.QFrame(parent=self.frame)
        self.frame_barra.setGeometry(QtCore.QRect(0, 0, 201, 591))
        self.frame_barra.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_barra.setStyleSheet("QFrame{\n"
"background-color: #ffffff;\n"
"}\n"
"QPushButton {\n"
"background-color: #ffffff;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #0068BB;\n"
"border-radius: 20px;\n"
"}")
        self.frame_barra.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_barra.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_barra.setObjectName("frame_barra")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_barra)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_resumen = QtWidgets.QPushButton(parent=self.frame_barra)
        self.btn_resumen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../models/logoIMSreduce.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_resumen.setIcon(icon)
        self.btn_resumen.setIconSize(QtCore.QSize(90, 90))
        self.btn_resumen.setShortcut("")
        self.btn_resumen.setCheckable(False)
        self.btn_resumen.setAutoRepeat(False)
        self.btn_resumen.setAutoExclusive(False)
        self.btn_resumen.setAutoDefault(False)
        self.btn_resumen.setDefault(False)
        self.btn_resumen.setFlat(True)
        self.btn_resumen.setObjectName("btn_resumen")
        self.verticalLayout_4.addWidget(self.btn_resumen)
        self.btn_inventario = QtWidgets.QPushButton(parent=self.frame_barra)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../models/inventario.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_inventario.setIcon(icon1)
        self.btn_inventario.setIconSize(QtCore.QSize(32, 32))
        self.btn_inventario.setFlat(True)
        self.btn_inventario.setObjectName("btn_inventario")
        self.verticalLayout_4.addWidget(self.btn_inventario)
        self.btn_entradas = QtWidgets.QPushButton(parent=self.frame_barra)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../models/entrada.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_entradas.setIcon(icon2)
        self.btn_entradas.setIconSize(QtCore.QSize(32, 32))
        self.btn_entradas.setFlat(True)
        self.btn_entradas.setObjectName("btn_entradas")
        self.verticalLayout_4.addWidget(self.btn_entradas)
        self.btn_salidas = QtWidgets.QPushButton(parent=self.frame_barra)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../models/salida.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_salidas.setIcon(icon3)
        self.btn_salidas.setIconSize(QtCore.QSize(32, 32))
        self.btn_salidas.setFlat(True)
        self.btn_salidas.setObjectName("btn_salidas")
        self.verticalLayout_4.addWidget(self.btn_salidas)
        self.btn_reportes = QtWidgets.QPushButton(parent=self.frame_barra)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../models/reportes.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_reportes.setIcon(icon4)
        self.btn_reportes.setIconSize(QtCore.QSize(32, 32))
        self.btn_reportes.setFlat(True)
        self.btn_reportes.setObjectName("btn_reportes")
        self.verticalLayout_4.addWidget(self.btn_reportes)
        self.btn_alertas = QtWidgets.QPushButton(parent=self.frame_barra)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../models/alertas.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_alertas.setIcon(icon5)
        self.btn_alertas.setIconSize(QtCore.QSize(32, 32))
        self.btn_alertas.setFlat(True)
        self.btn_alertas.setObjectName("btn_alertas")
        self.verticalLayout_4.addWidget(self.btn_alertas)
        self.btn_configuracion = QtWidgets.QPushButton(parent=self.frame_barra)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../models/configuracion.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_configuracion.setIcon(icon6)
        self.btn_configuracion.setIconSize(QtCore.QSize(32, 32))
        self.btn_configuracion.setFlat(True)
        self.btn_configuracion.setObjectName("btn_configuracion")
        self.verticalLayout_4.addWidget(self.btn_configuracion)
        self.frame_cuerpo = QtWidgets.QFrame(parent=self.frame)
        self.frame_cuerpo.setGeometry(QtCore.QRect(200, 190, 601, 401))
        self.frame_cuerpo.setStyleSheet("QToolBox::tab{\n"
"background-color: rgb(207, 207, 207);\n"
"border-radius: 5px;\n"
"color: #0068BB;\n"
"font: 12pt \"Swis721 BlkCn BT\";\n"
"}\n"
"QToolBox::tab::selected{\n"
"background-color: rgb(20, 200, 220);\n"
"border-radius: 5px;\n"
"color: #000000;\n"
"font: 12pt \"Swis721 BlkCn BT\";\n"
"}")
        self.frame_cuerpo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cuerpo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cuerpo.setObjectName("frame_cuerpo")
        self.toolBox3 = QtWidgets.QToolBox(parent=self.frame_cuerpo)
        self.toolBox3.setGeometry(QtCore.QRect(-2, -2, 591, 401))
        self.toolBox3.setObjectName("toolBox3")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 591, 311))
        self.page.setObjectName("page")
        self.list_totproductos = QtWidgets.QListView(parent=self.page)
        self.list_totproductos.setGeometry(QtCore.QRect(10, 10, 571, 281))
        self.list_totproductos.setObjectName("list_totproductos")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../models/paginas.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox3.addItem(self.page, icon7, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 591, 311))
        self.page_3.setObjectName("page_3")
        self.list_producstockbajo = QtWidgets.QListView(parent=self.page_3)
        self.list_producstockbajo.setGeometry(QtCore.QRect(10, 10, 571, 291))
        self.list_producstockbajo.setObjectName("list_producstockbajo")
        self.toolBox3.addItem(self.page_3, icon7, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 591, 311))
        self.page_2.setObjectName("page_2")
        self.table_movrecientes = QtWidgets.QTableView(parent=self.page_2)
        self.table_movrecientes.setGeometry(QtCore.QRect(10, 10, 571, 291))
        self.table_movrecientes.setObjectName("table_movrecientes")
        self.toolBox3.addItem(self.page_2, icon7, "")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(200, 0, 601, 181))
        self.frame_2.setStyleSheet("background-color: #ffffff")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.logo_letras = QtWidgets.QLabel(parent=self.frame_2)
        self.logo_letras.setGeometry(QtCore.QRect(120, 0, 291, 181))
        self.logo_letras.setText("")
        self.logo_letras.setPixmap(QtGui.QPixmap("../models/logoIMSreduce2.png"))
        self.logo_letras.setScaledContents(True)
        self.logo_letras.setObjectName("logo_letras")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_superior.setGeometry(QtCore.QRect(410, 0, 181, 42))
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setAutoFillBackground(False)
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: #ffffff;\n"
"}\n"
"QPushButton {\n"
"background-color: #ffffff;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #0068BB;\n"
"border-radius: 20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_minimizar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_minimizar.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../models/minimizar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_minimizar.setIcon(icon8)
        self.btn_minimizar.setIconSize(QtCore.QSize(32, 32))
        self.btn_minimizar.setFlat(True)
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_achicar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_achicar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_achicar.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../models/hacerchico.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_achicar.setIcon(icon9)
        self.btn_achicar.setIconSize(QtCore.QSize(32, 32))
        self.btn_achicar.setObjectName("btn_achicar")
        self.horizontalLayout.addWidget(self.btn_achicar)
        self.btn_agrandar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_agrandar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_agrandar.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../models/hacergrande.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_agrandar.setIcon(icon10)
        self.btn_agrandar.setIconSize(QtCore.QSize(32, 32))
        self.btn_agrandar.setObjectName("btn_agrandar")
        self.horizontalLayout.addWidget(self.btn_agrandar)
        self.btn_cerrar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_cerrar.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../models/cerrar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cerrar.setIcon(icon11)
        self.btn_cerrar.setIconSize(QtCore.QSize(32, 32))
        self.btn_cerrar.setFlat(True)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.bt_ocultar = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_ocultar.setGeometry(QtCore.QRect(-20, 100, 75, 40))
        self.bt_ocultar.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_ocultar.setStyleSheet("QPushButton:hover {\n"
"background-color: #0068BB;\n"
"border-radius: 20px;\n"
"}")
        self.bt_ocultar.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../models/izquierda.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_ocultar.setIcon(icon12)
        self.bt_ocultar.setIconSize(QtCore.QSize(32, 32))
        self.bt_ocultar.setFlat(True)
        self.bt_ocultar.setObjectName("bt_ocultar")
        self.bt_mostrar = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_mostrar.setGeometry(QtCore.QRect(-20, 40, 75, 40))
        self.bt_mostrar.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_mostrar.setStyleSheet("QPushButton:hover {\n"
"background-color: #0068BB;\n"
"border-radius: 20px;\n"
"}")
        self.bt_mostrar.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../models/derecha.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_mostrar.setIcon(icon13)
        self.bt_mostrar.setIconSize(QtCore.QSize(32, 32))
        self.bt_mostrar.setFlat(True)
        self.bt_mostrar.setObjectName("bt_mostrar")
        self.frame_2.raise_()
        self.frame_barra.raise_()
        self.frame_cuerpo.raise_()
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_inventario.setText(_translate("MainWindow", "Inventario"))
        self.btn_entradas.setText(_translate("MainWindow", "Entradas"))
        self.btn_salidas.setText(_translate("MainWindow", "Salidas"))
        self.btn_reportes.setText(_translate("MainWindow", "Reportes"))
        self.btn_alertas.setText(_translate("MainWindow", "Alertas"))
        self.btn_configuracion.setText(_translate("MainWindow", "Configuración"))
        self.toolBox3.setItemText(self.toolBox3.indexOf(self.page), _translate("MainWindow", "Total de productos"))
        self.toolBox3.setItemText(self.toolBox3.indexOf(self.page_3), _translate("MainWindow", "Productos con stock bajo"))
        self.toolBox3.setItemText(self.toolBox3.indexOf(self.page_2), _translate("MainWindow", "Movimientos recientes"))
