# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 648)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setStyleSheet("QFrame{\n"
"    background-color: #0068BC;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    font: 20pt \"Swis721 BlkCn BT\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background-color:#5DADE2; \n"
"    min-width: 60px;\n"
"    min-height: 60px;\n"
"    border-radius: 30px; \n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame_superior)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(377, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../models/minimizar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_minimizar.setIcon(icon)
        self.btn_minimizar.setIconSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_achicar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_achicar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../models/hacerchico.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_achicar.setIcon(icon1)
        self.btn_achicar.setIconSize(QtCore.QSize(40, 40))
        self.btn_achicar.setObjectName("btn_achicar")
        self.horizontalLayout.addWidget(self.btn_achicar)
        self.btn_agrandar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_agrandar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../models/hacergrande.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_agrandar.setIcon(icon2)
        self.btn_agrandar.setIconSize(QtCore.QSize(40, 40))
        self.btn_agrandar.setObjectName("btn_agrandar")
        self.horizontalLayout.addWidget(self.btn_agrandar)
        self.btn_cerrar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../models/cerrar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cerrar.setIcon(icon3)
        self.btn_cerrar.setIconSize(QtCore.QSize(40, 40))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_cuerpo = QtWidgets.QFrame(parent=self.frame)
        self.frame_cuerpo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_cuerpo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_cuerpo.setLineWidth(0)
        self.frame_cuerpo.setObjectName("frame_cuerpo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_cuerpo)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_barra = QtWidgets.QFrame(parent=self.frame_cuerpo)
        self.frame_barra.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_barra.setStyleSheet("QFrame {\n"
"    background-color: #60B0C3\n"
"}\n"
"QPushButton{\n"
"    background-color: #0068BC;       \n"
"    color: #FFFFFF;                    /* Texto blanco */\n"
"    border: none;                    /* Sin borde de línea */\n"
"    border-radius: 12px;             /* Bordes redondeados */\n"
"    padding: 10px 20px;              /* Relleno interno */\n"
"    font: bold 12pt \"Arial\"; \n"
"}\n"
"QPushButton#btn_resumen{\n"
"background-color: #ffffff\n"
"}\n"
"QPushButton#btn_resumen:hover{\n"
"background-color: #5DADE2;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5DADE2;       /* Color cuando el mouse pasa encima */\n"
"}\n"
"\n"
"")
        self.frame_barra.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_barra.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_barra.setLineWidth(0)
        self.frame_barra.setObjectName("frame_barra")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_barra)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_resumen = QtWidgets.QPushButton(parent=self.frame_barra)
        self.btn_resumen.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../models/logoIMSreduce.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_resumen.setIcon(icon4)
        self.btn_resumen.setIconSize(QtCore.QSize(120, 120))
        self.btn_resumen.setObjectName("btn_resumen")
        self.verticalLayout_3.addWidget(self.btn_resumen)
        self.btn_inventario = QtWidgets.QPushButton(parent=self.frame_barra)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../models/inventario.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_inventario.setIcon(icon5)
        self.btn_inventario.setIconSize(QtCore.QSize(30, 30))
        self.btn_inventario.setObjectName("btn_inventario")
        self.verticalLayout_3.addWidget(self.btn_inventario)
        self.btn_entradas = QtWidgets.QPushButton(parent=self.frame_barra)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../models/entrada.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_entradas.setIcon(icon6)
        self.btn_entradas.setIconSize(QtCore.QSize(30, 30))
        self.btn_entradas.setObjectName("btn_entradas")
        self.verticalLayout_3.addWidget(self.btn_entradas)
        self.btn_salidas = QtWidgets.QPushButton(parent=self.frame_barra)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../models/salida.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_salidas.setIcon(icon7)
        self.btn_salidas.setIconSize(QtCore.QSize(30, 30))
        self.btn_salidas.setObjectName("btn_salidas")
        self.verticalLayout_3.addWidget(self.btn_salidas)
        self.btn_reportes = QtWidgets.QPushButton(parent=self.frame_barra)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../models/reportes.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_reportes.setIcon(icon8)
        self.btn_reportes.setIconSize(QtCore.QSize(30, 30))
        self.btn_reportes.setObjectName("btn_reportes")
        self.verticalLayout_3.addWidget(self.btn_reportes)
        self.btn_configuracion = QtWidgets.QPushButton(parent=self.frame_barra)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../models/configuracion.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_configuracion.setIcon(icon9)
        self.btn_configuracion.setIconSize(QtCore.QSize(30, 30))
        self.btn_configuracion.setObjectName("btn_configuracion")
        self.verticalLayout_3.addWidget(self.btn_configuracion)
        self.horizontalLayout_2.addWidget(self.frame_barra)
        self.frame_contenido = QtWidgets.QFrame(parent=self.frame_cuerpo)
        self.frame_contenido.setStyleSheet("background-color: #99D8DD")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_contenido)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_logo = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_logo.setStyleSheet("QFrame{\n"
"    background-color: #ffffff\n"
"}\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover { \n"
"    background-color:#5DADE2; \n"
"    min-width: 60px;\n"
"    min-height: 60px;\n"
"    border-radius: 30px; \n"
"}")
        self.frame_logo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_logo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_ocultar = QtWidgets.QPushButton(parent=self.frame_logo)
        self.bt_ocultar.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../models/izquierda.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_ocultar.setIcon(icon10)
        self.bt_ocultar.setIconSize(QtCore.QSize(50, 50))
        self.bt_ocultar.setObjectName("bt_ocultar")
        self.horizontalLayout_3.addWidget(self.bt_ocultar)
        self.bt_mostrar = QtWidgets.QPushButton(parent=self.frame_logo)
        self.bt_mostrar.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../models/derecha.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_mostrar.setIcon(icon11)
        self.bt_mostrar.setIconSize(QtCore.QSize(50, 50))
        self.bt_mostrar.setObjectName("bt_mostrar")
        self.horizontalLayout_3.addWidget(self.bt_mostrar)
        spacerItem3 = QtWidgets.QSpacerItem(131, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.logo_letras = QtWidgets.QLabel(parent=self.frame_logo)
        self.logo_letras.setMaximumSize(QtCore.QSize(220, 160))
        self.logo_letras.setText("")
        self.logo_letras.setPixmap(QtGui.QPixmap("../models/logoIMSreduce2.png"))
        self.logo_letras.setScaledContents(True)
        self.logo_letras.setObjectName("logo_letras")
        self.horizontalLayout_3.addWidget(self.logo_letras)
        spacerItem4 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.frame_logo)
        self.frame_informacion = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_informacion.setStyleSheet("QFrame{\n"
"    background-color: #C0E4E5\n"
"}\n"
"QToolBox::tab{\n"
"background-color: #61ADC1;\n"
"border-radius: 5px;\n"
"color: #ffffff;\n"
"font: 12pt \"Swis721 BlkCn BT\";\n"
"}\n"
"QToolBox::tab::selected{\n"
"background-color: #005999;\n"
"border-radius: 5px;\n"
"color: #ffffff;\n"
"font: 12pt \"Swis721 BlkCn BT\";\n"
"}")
        self.frame_informacion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_informacion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_informacion.setObjectName("frame_informacion")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_informacion)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_adicional = QtWidgets.QFrame(parent=self.frame_informacion)
        self.frame_adicional.setStyleSheet("QFrame {\n"
"    background-color: #C0E4E5\n"
"}\n"
"QPushButton{\n"
"    background-color: #0068BC;       \n"
"    color: #FFFFFF;                    /* Texto blanco */\n"
"    border: 1px solid #ccc;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-right: none; /* Elimina borde derecho para unión */\n"
"    padding: 8px;              /* Relleno interno */\n"
"    font: bold 12pt \"Arial\"; \n"
"}\n"
"QPushButton#btn_resumen{\n"
"background-color: #ffffff\n"
"}\n"
"QPushButton#btn_resumen:hover{\n"
"background-color: #5DADE2;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5DADE2;       /* Color cuando el mouse pasa encima */\n"
"}")
        self.frame_adicional.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_adicional.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_adicional.setObjectName("frame_adicional")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_adicional)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_alertas = QtWidgets.QFrame(parent=self.frame_adicional)
        self.frame_alertas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_alertas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_alertas.setObjectName("frame_alertas")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_alertas)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_alertas = QtWidgets.QPushButton(parent=self.frame_alertas)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../models/alertas.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_alertas.setIcon(icon12)
        self.btn_alertas.setIconSize(QtCore.QSize(30, 30))
        self.btn_alertas.setObjectName("btn_alertas")
        self.horizontalLayout_5.addWidget(self.btn_alertas)
        self.label_notificaciones = QtWidgets.QLabel(parent=self.frame_alertas)
        self.label_notificaciones.setEnabled(False)
        self.label_notificaciones.setStyleSheet("QLabel {\n"
"    background-color: red;\n"
"    border: 1px solid #ccc;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-left: none; /* Elimina borde izquierdo para unión */\n"
"    padding: 5px;\n"
"    color: black;\n"
"    font: bold 12pt \"Arial\"; \n"
"}")
        self.label_notificaciones.setObjectName("label_notificaciones")
        self.horizontalLayout_5.addWidget(self.label_notificaciones)
        self.horizontalLayout_5.setStretch(0, 8)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_4.addWidget(self.frame_alertas)
        self.frame_fecha = QtWidgets.QFrame(parent=self.frame_adicional)
        self.frame_fecha.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_fecha.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_fecha.setObjectName("frame_fecha")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_fecha)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.dateTimeEdit_tiempo = QtWidgets.QDateTimeEdit(parent=self.frame_fecha)
        self.dateTimeEdit_tiempo.setEnabled(False)
        self.dateTimeEdit_tiempo.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #d1f4f9;       /* Fondo celeste claro */\n"
"    color: #003366;                  /* Texto azul oscuro */\n"
"    border: 2px solid #0077b6;       /* Borde azul */\n"
"    border-radius: 10px;\n"
"    padding: 5px 8px;\n"
"    font: bold 16px \"Segoe UI\";\n"
"    height: 30px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"QDateTimeEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #0077b6;\n"
"    image: url(:/icons/calendar.png); /* Usa un ícono personalizado si lo tienes */\n"
"    background: transparent;\n"
"}\n"
"\n"
"QDateTimeEdit:focus {\n"
"    border: 2px solid #00b4d8; /* Azul más claro al enfocar */\n"
"    background-color: #caf0f8;\n"
"}")
        self.dateTimeEdit_tiempo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateTimeEdit_tiempo.setObjectName("dateTimeEdit_tiempo")
        self.verticalLayout_10.addWidget(self.dateTimeEdit_tiempo)
        self.horizontalLayout_4.addWidget(self.frame_fecha)
        self.horizontalLayout_4.setStretch(0, 7)
        self.horizontalLayout_4.setStretch(1, 7)
        self.verticalLayout_5.addWidget(self.frame_adicional)
        self.toolBox = QtWidgets.QToolBox(parent=self.frame_informacion)
        self.toolBox.setObjectName("toolBox")
        self.page_resumen = QtWidgets.QWidget()
        self.page_resumen.setGeometry(QtCore.QRect(0, 0, 567, 239))
        self.page_resumen.setObjectName("page_resumen")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_resumen)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.page_resumen)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_3)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../models/paginas.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.page_resumen, icon13, "")
        self.page_stock = QtWidgets.QWidget()
        self.page_stock.setGeometry(QtCore.QRect(0, 0, 567, 239))
        self.page_stock.setObjectName("page_stock")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_stock)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.page_stock)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        self.toolBox.addItem(self.page_stock, icon13, "")
        self.page_movimientos = QtWidgets.QWidget()
        self.page_movimientos.setGeometry(QtCore.QRect(0, 0, 567, 239))
        self.page_movimientos.setObjectName("page_movimientos")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_movimientos)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_movimientos)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidget)
        self.toolBox.addItem(self.page_movimientos, icon13, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 7)
        self.verticalLayout_4.addWidget(self.frame_informacion)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 5)
        self.horizontalLayout_2.addWidget(self.frame_contenido)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout_2.addWidget(self.frame_cuerpo)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Ventana Resumen"))
        self.btn_inventario.setText(_translate("Form", "Inventario"))
        self.btn_entradas.setText(_translate("Form", "Entradas"))
        self.btn_salidas.setText(_translate("Form", "Salidas"))
        self.btn_reportes.setText(_translate("Form", "Reportes"))
        self.btn_configuracion.setText(_translate("Form", "Configuracion"))
        self.btn_alertas.setText(_translate("Form", "Alertas"))
        self.label_notificaciones.setText(_translate("Form", "0"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_resumen), _translate("Form", "Total de productos"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_stock), _translate("Form", "Productos con stock bajo"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_movimientos), _translate("Form", "Movimientos recientes"))
